### ISSUE TITLE
Trying to migrate Bbii to Yii2, having javascript issues...

### ISSUE THREAD

**Issue by davidjeddy** [rbacui/bbii1#5]
I know this is probably WAAAY out of support but I've been stuck on this for 3 days, hoping I could a little help.

In views/settings/layout I have convert the dialog widget over to Yii2, this is the result:

```
Dialog::begin([
	'id'           => 'dlgEditForum',
	'clientOptions'=> [
		'closeButton' => true,
		'autoOpen' => false,
		// @todo get the resolution for this issue - DJE : 2015-05-21
		'buttons'  => [
			[ 'text' => 'Test',   'click' => new JsExpression('function(){ $( this ).dialog( "close" ) }') ],
			[ 'text' => 'Delete', 'click' => new JsExpression('function(){ deleteForum(' . Yii::$app->urlManager->createAbsoluteUrl('forum/setting/deleteForum') .') }') ],
		],
		'modal'    => true,
		'show'     => 'fade',
		'title'    => 'Edit',
		'width'    => 800,
	],
]);

echo $this->render('_editForum', array(
	'model' => $model,
));

Dialog::end();
```

The problem is in the buttons. I get the error "Uncaught SyntaxError: missing ) after argument list". 

Can I get a little help on this?

**Comment by rbacui** [comment]
I have insufficient knowledge of Yii2 to help you. But I do wonder whether it is wise to try to migrate BBii to Yii2. Starting from scratch is probably easier and less work.

**Comment by davidjeddy** [comment]
Sorted, Yii2 Bbii version will eventually be available publicly.
